DROP TABLE OWNER;

CREATE TABLE OWNER(
	ID VARCHAR2(200) PRIMARY KEY,
	NAME VARCHAR2(200) NOT NULL,
	AGE NUMBER(5) DEFAULT 20,
	ADDRESS VARCHAR2(300)
);

SELECT * FROM OWNER;

DROP TABLE PET;

CREATE TABLE PET(
	PIN VARCHAR2(300) PRIMARY KEY,
	NAME VARCHAR2(200) NOT NULL,
	AGE NUMBER(5) DEFAULT 1,
	OWNERID VARCHAR2(200),
	GENDER CHAR(1) DEFAULT 'M' NOT NULL CONSTRAINT CHECK_CHAR CHECK(GENDER IN('M','W')),
	CONSTRAINT PET_FK FOREIGN KEY(OWNERID) REFERENCES OWNER(ID)
);

SELECT * FROM PET;