--PLAYER 테이블에서 TRAM_ID 가 'K01'인 선수 이름을 내이름으로 바꾸기
UPDATE PLAYER 
SET	PLAYER_NAME ='한동석'
WHERE TEAM_ID = 'K01';

SELECT * FROM PLAYER
WHERE TEAM_ID ='K01';

--PLAYER 테이블에서 POSITION이 MD인 선수 삭제하기
DELETE FROM PLAYER WHERE POSITION ='MF';

SELECT * FROM PLAYER
WHERE "POSITION" ='MF';

--AS (ALIAS)
SELECT PLAYER_ID AS 선수번호 FROM PLAYER; --항상 ''은 값으로 인식하므로 빼주기, 띄어쓰기넣고싶으면 쌍따옴표 !
SELECT PLAYER_ID AS "선수 번호" FROM PLAYER;
SELECT PLAYER_ID "선수 번호" FROM PLAYER;
SELECT PLAYER_ID "선수 번호",PLAYER_NAME "선수 이름" FROM PLAYER;

--PLAYER 테이블에서 BACK_NUM "등 번호"로 , NICKNAME을 선수번호로 바꿔 검색
SELECT BACK_NO AS "등 번호", NICKNAME AS "선수 별명"FROM PLAYER;

SELECT PLAYER.TEAM_ID, TEAM.TEAM_ID FROM PLAYER, TEAM;

SELECT P.TEAM_ID,T.TEAM_ID FROM PLAYER P, TEAM T;