--EMP 테이블에서 사원번호로 DEPT 테이블의 지역 검색하기
SELECT * FROM EMP;	--DEPTNO FK
SELECT * FROM DEPT; --DEPTNO PK

SELECT EMP.DEPTNO, EMP.ENAME, EMP.JOB, DEPT.LOC FROM EMP JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO; -- 겹치는 테이블은 소속을 써주자 !

--PLAYER TABLE에서 송종국 선수가 속한 팀의 전화번호 검색
SELECT * FROM PLAYER;
SELECT * FROM TEAM;

SELECT P.TEAM_ID, P.PLAYER_NAME , T.TEL FROM PLAYER P JOIN TEAM T
ON P.TEAM_ID = T.TEAM_ID AND P.PLAYER_NAME = '송종국';

--JOBS TABLE에서 JOB_ID 로 EMPLOYEES의 EMAIL,JOB_TITLE, 성, 이름 검색
SELECT * FROM JOBS;
SELECT * FROM EMPLOYEES;

SELECT J.JOB_ID , J.JOB_TITLE , E.EMAIL ,E.LAST_NAME ||' '||E.FIRST_NAME 이름 FROM JOBS J JOIN EMPLOYEES E
ON J.JOB_ID = E.JOB_ID ;


SELECT * FROM DEPT;

--급여로 등급 나누기
SELECT * FROM SALGRADE;
SELECT * FROM EMP;

SELECT E.EMPNO, E.ENAME ,S.GRADE,E.SAL FROM SALGRADE S JOIN EMP E
ON E.SAL BETWEEN S.LOSAL AND S.HISAL ; --등호가 없으니 비등가조인

-- 하나를 더 조인하고싶으면?
-- CARDINALITY, COST 둘다 아래와동일
SELECT E.EMPNO, E.ENAME ,S.GRADE,E.SAL FROM SALGRADE S JOIN EMP E
ON E.SAL BETWEEN S.LOSAL AND S.HISAL 
JOIN DEPT D
ON E.DEPTNO = D.DEPTNO;

-- CARDINALITY, COST 둘다 위와동일
SELECT E.EMPNO, D.DNAME, E.ENAME, S.GRADE, E.SAL FROM
SALGRADE S, EMP E, DEPT D
WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL AND E.DEPTNO = D.DEPTNO;
