SELECT * FROM PLAYER ORDER BY PLAYER_ID DESC;

-- PLAYER TABLE에서 INDEX_NAME으로 사용할 수 있는건 PLAYER_PK 다.
SELECT I.INDEX_NAME FROM USER_IND_COLUMNS I
WHERE TABLE_NAME = 'PLAYER';

SELECT /*+INDEX_DESC(PLAYER PLAYER_PK)*/ * FROM PLAYER;
SELECT /*+INDEX(PLAYER PLAYER_PK)*/ * FROM PLAYER;

-- 전체게시글이나 전체댓글 이런걸 최신순 오래된순으로 가져오기 좋다.