CREATE TABLE COPY_PLAYER AS SELECT * FROM HR.PLAYER;
SELECT * FROM COPY_PLAYER CP JOIN HR.TEAM T
ON CP.TEAM_ID = T.TEAM_ID;

--scott 테이블에서 SALGRADE를 복사한 후 GRADE 컬럼명을 LEVEL로 변경,값을 반대로 바꾸기
--5->1
--4->2
--...
--1->5
CREATE TABLE SALGRADE AS SELECT * FROM SCOTT.SALGRADE;
ALTER TABLE SALGRADE RENAME COLUMN GRADE TO "LEVEL";
UPDATE SALGRADE
SET "LEVEL" = 6-"LEVEL";
SELECT * FROM SALGRADE;